:original_name: modelarts_13_0007.html

.. _modelarts_13_0007:

Error Occurs When the ipynb File Is Saved
=========================================

Symptom
-------

The following error occurs when a user saves the **ipynb** file on the Jupyter page accessed using a notebook instance: **The file has changed on disk since the last time we opened or saved it.** xxxx

Possible Cause
--------------

The same file is modified in two or more development environments at the same time, which causes file saving failure.

Solution
--------

Close the same file in other development environments. See :ref:`Figure 1 <en-us_topic_0000002079104225__fig18822143215509>`.

.. _en-us_topic_0000002079104225__fig18822143215509:

.. figure:: /_static/images/en-us_image_0000002043183700.png
   :alt: **Figure 1** Closing the development environment

   **Figure 1** Closing the development environment
